name = "Neo4jQuery"
uuid = "73bf9368-8aa0-4807-ab74-772e1b9f394f"
version = "0.3.1"
authors = ["Marius Fersigan <marius.fersigan@gmail.com> and contributors"]

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
Aqua = "0.8"
Base64 = "1"
Dates = "1"
HTTP = "1"
JSON = "1"
Pkg = "1"
Test = "1"
TimeZones = "1"
julia = "1.12"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Pkg", "Test"]
