name = "Neo4jQuery"
uuid = "73bf9368-8aa0-4807-ab74-772e1b9f394f"
authors = ["Marius Fersigan <marius.fersigan@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
